<?php

declare(strict_types=1);

return [
    0 => [
        'type' => 'metric',
        'segment' => 'actions',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'Actions_ActionsInVisit',
    ],
    1 => [
        'type' => 'metric',
        'segment' => 'daysSinceFirstVisit',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_DaysSinceFirstVisit',
    ],
    2 => [
        'type' => 'metric',
        'segment' => 'daysSinceLastEcommerceOrder',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_DaysSinceLastEcommerceOrder',
    ],
    3 => [
        'type' => 'metric',
        'segment' => 'daysSinceLastVisit',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_DaysSinceLastVisit',
    ],
    4 => [
        'type' => 'metric',
        'segment' => 'events',
        'acceptedValues' => 'To select all visits who triggered an Event, use: &segment=events>0',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'Events_Events',
    ],
    5 => [
        'type' => 'metric',
        'segment' => 'visitLocalMinute',
        'acceptedValues' => '0, 1, 2, 3, ..., 67, 57, 58, 59',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnLocalMinute',
    ],
    6 => [
        'type' => 'metric',
        'segment' => 'interactions',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_NbInteractions',
        'acceptedValuesKey' => 'General_AnyPositiveInteger',
    ],
    7 => [
        'type' => 'metric',
        'segment' => 'searches',
        'acceptedValues' => 'To select all visits who used internal Site Search, use: &segment=searches>0',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_NbSearches',
    ],
    8 => [
        'type' => 'metric',
        'segment' => 'visitCount',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_NumberOfVisits',
    ],
    9 => [
        'type' => 'metric',
        'segment' => 'secondsSinceFirstVisit',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_SecondsSinceFirstVisit',
    ],
    10 => [
        'type' => 'metric',
        'segment' => 'secondsSinceLastEcommerceOrder',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_SecondsSinceLastEcommerceOrder',
    ],
    11 => [
        'type' => 'metric',
        'segment' => 'secondsSinceLastVisit',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_SecondsSinceLastVisit',
    ],
    12 => [
        'type' => 'metric',
        'segment' => 'visitDuration',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_ColumnVisitDuration',
    ],
    13 => [
        'type' => 'metric',
        'segment' => 'visitIp',
        'acceptedValues' => '13.54.122.1. Select IP ranges with notation: <code>visitIp>13.54.122.0;visitIp<13.54.122.255</code>',
        'permission' => '1',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_VisitorIP',
    ],
    14 => [
        'type' => 'dimension',
        'segment' => 'aiAgentName',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'AIAgents_AIAgentName',
    ],
    15 => [
        'type' => 'dimension',
        'segment' => 'browserName',
        'acceptedValues' => 'FireFox, Internet Explorer, Chrome, Safari, Opera etc.',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_ColumnBrowser',
    ],
    16 => [
        'type' => 'dimension',
        'segment' => 'browserCode',
        'acceptedValues' => 'FF, IE, CH, SF, OP etc.',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_BrowserCode',
    ],
    17 => [
        'type' => 'dimension',
        'segment' => 'browserEngine',
        'acceptedValues' => 'Trident, WebKit, Presto, Gecko, Blink, etc.',
        'suggestedValuesCallback' => '\\DeviceDetector\\Parser\\Client\\Browser\\Engine::getAvailableEngines',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_BrowserEngine',
    ],
    18 => [
        'type' => 'dimension',
        'segment' => 'browserVersion',
        'acceptedValues' => '1.0, 8.0, etc.',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_BrowserVersion',
    ],
    19 => [
        'type' => 'dimension',
        'segment' => 'deviceBrand',
        'acceptedValues' => '2E, 3GNET, 3GO, 3Q, 4Good, 4ife, 5IVE, 7 Mobile, 7Ke tree, 10moons, 360, 8848, A&K, A1, A95X, AAUW, Accent, Accesstyle, ACD, Ace, Aceline, Acepad, Acer, Acteck, actiMirror, Adreamer, Adronix, Advan, Advance, Advantage Air, AEEZO, AFFIX, AfriOne, AGM, AG Mobile, AI+, AIDATA, AileTV, Ainol, Airis, Airness, AIRON, Airpha, Airtel, Airties, AirTouch, AIS, Aiuto, Aiwa, Ajib, Akai, AKIRA, Alba, Alcatel, Alcor, ALDI NORD, ALDI SÜD, Alfawise, Alienware, Aligator, AllCall, AllDocube, allente, ALLINmobile, All Star, Allview, Allwinner, Alps, alpsmart, Altech UEC, Altibox, Altice, Altimo, altron, Altus, AMA, Amazon, Amazon Basics, AMCV, AMGOO, Amigoo, Amino, Amoi, ANBERNIC, ANCEL, andersson, Andowl, Angelcare, AngelTech, Anker, Anry, ANS, ANXONIT, AOC, Aocos, Aocwei, AOpen, Aoro, Aoson, AOYODKG, ApoloSign, Apple, Aquarius, Archos, Arian Space, Arival, Ark, ArmPhone, Arnova, ARRIS, Artel, Artizlee, ArtLine, Arçelik, Asano, Asanzo, Ask, Aspera, ASSE, Assistant, astro (MY), Astro (UA), Asus, AT&T, Athesi, Atlantic Electrics, Atmaca Elektronik, ATMAN, ATMPC, ATOL, Atom, Atouch, Atozee, Attila, Atvio, Audiovox, AUPO, AURIS, Autan, AUX, Avaya, Avenzo, AVH, Avvio, Awow, AWOX, AXEN, Axioo, AXXA, Axxion, AYA, AYYA, Azeyou, AZOM, Azumi Mobile, Azupik, b2m, Backcell, BAFF, BangOlufsen, Barnes & Noble, BARTEC, BAUHN, BBK, BB Mobile, BDF, BDQ, BDsharing, Beafon, Becker, Beeline, Beelink, Beetel, Beista, Beko, Bell, Bellphone, Benco, Benesse, BenQ, BenQ-Siemens, BenWee, Benzo, Beyond, Bezkam, BGH, Biegedy, Bigben, BIHEE, BilimLand, Billion, Billow, BioRugged, Bird, Bitel, Bitmore, Bittium, Bkav, Black Bear, Black Box, Black Fox, Blackpcs, Blackphone, Blackton, Blackview, Blaupunkt, Bleck, BLISS, Blloc, Blow, Blu, Bluboo, Bluebird, Bluedot, Bluegood, BlueSky, Bluewave, BluSlate, BMAX, Bmobile, BMW, BMXC, BNCF, Bobarry, bogo, Bolva, Bookeen, Boost, Botech, Boway, bq, Bqeel, BrandCode, Brandt, BRAVE, Bravis, BrightSign, Brigmton, Brondi, BROR, BS Mobile, Bubblegum, Bundy, Bush, BuzzTV, BYD, BYJU\'S, BYYBUO, C5 Mobile, CADENA, CAGI, Caixun, CALME, Camfone, Canaima, Canal+, Canal Digital, Canguro, Capitel, Captiva, Carbon Mobile, Carrefour, Casio, Casper, Cat, Cavion, CCIT, Cecotec, Ceibal, Celcus, Celkon, Cell-C, Cellacom, CellAllure, Cellution, CENTEK, Centric, CEPTER, CG Mobile, CGV, Chainway, Changhong, CHCNAV, Cherry Mobile, Chico Mobile, ChiliGreen, China Mobile, China Telecom, Chuwi, C Idea, CipherLab, Citycall, CKK Mobile, Claresta, Clarmin, CLAYTON, ClearPHONE, Clementoni, Cloudfone, Cloud Mobile, Clout, Clovertek, CMF, CnM, Cobalt, Coby Kyros, Cogeco, COLORROOM, Colors, Comio, CommScope, Compal, Compaq, COMPUMAX, ComTrade Tesla, Conceptum, Concord, ConCorde, Condor, Connectce, Connex, Conquest, CONSUNG, Continental Edison, Contixo, coocaa, COOD-E, Coolpad, Coopers, CORN, Cosmote, Covia, Cowon, COYOTE, CPDEVICE, CreNova, Crescent, Crestron, Cricket, Crius Mea, Crony, Crosscall, Crown, Ctroniq, Cube, CUBOT, CUD, Cuiud, Cultraview, CVTE, Cwowdefu, CX, Cyrus, D-Link, D-Tech, Daewoo, Danew, DangcapHD, Dany, Daria, DASS, Datalogic, Datamini, Datang, Datawind, Datsun, Dawlance, DbPhone, Dbtel, Dcode, DEALDIG, DEC, Dell, Denali, Denka, Denver, Desay, DeWalt, DEXP, DEYI, DF, DGTEC, DIALN, Dialog, Dicam, Digi, Digicel, DIGICOM, Digidragon, DIGIFORS, Digihome, Digiland, Digit, Digma, DIJITSU, DIKOM, DIMO, Dinalink, Dinax, DING DING, Diofox, DIORA, DISH, Disney, Ditecma, Diva, DiverMax, Divisat, DIXON, DL, DMOAO, DNS, DoCoMo, Doffler, Dolamee, Dom.ru, Doogee, Doopro, Doov, Dopod, Doppio, Dora, DORLAND, Doro, DPA, DRAGON, Dragon Touch, Dreamgate, Dream Multimedia, DreamStar, Droidlogic, Droxio, DSDevices, DSIC, Dtac, DUDU AUTO, Dune HD, DUNNS Mobile, DuoTV, Durabook, Duubee, Dykemann, Dyon, E-Boda, E-Ceros, E-TACHI, E-tel, Eagle, EagleSoar, EAS Electric, Easypix, EBEN, EBEST, Echo Mobiles, ecom, ECON, ECOO, EcoStar, ECS, Edanix, Edenwood, EE, EFT, EGL, EGOTEK, Ehlel, Einstein, EKO, Eks Mobility, EKT, ELARI, ELE-GATE, Elecson, Electroneum, ELECTRONIA, Elekta, Elektroland, Element, Elenberg, Elephone, Elevate, Elista, elit, Elong Mobile, Eltex, Ematic, Emporia, ENACOM, ENDURO, Energizer, Energy Sistem, Engel, ENIE, Enot, eNOVA, Entity, Envizen, Ephone, Epic, EPIK Learning, Epik One, Eplutus, Epson, Equator, Ergo, Ericsson, Erisson, Essential, Essentielb, eSTAR, ETOE, Eton, eTouch, Etuline, Eudora, Eurocase, EUROLUX, Eurostar, Evercoss, Everest, Everex, Everfine, Everis, Evertek, Evolio, Evolveo, Evoo, EVPAD, EvroMedia, evvoli, EWIS, EXCEED, Exertis, Exmart, ExMobile, EXO, Explay, Express LUCK, ExtraLink, Extrem, Eyemoo, EYU, Ezio, Ezze, F&U, F+, F2 Mobile, F150, Facebook, Facetel, Facime, Fairphone, Famoco, Famous, Fantec, Fanvace, FaRao Pro, Farassoo, FarEasTone, Fengxiang, Fenoti, FEONAL, Fero, FFF SmartLife, Figgers, FiGi, FiGO, FiiO, Filimo, FILIX, FinePower, FINIX, Finlux, FireFly Mobile, FISE, Fision, FITCO, Fluo, Fly, FLYCAT, FLYCOAY, FMT, FNB, FNF, Fobem, Fondi, Fonos, FONTEL, FOODO, FORME, Formovie, Formuler, Forstar, Fortis, FortuneShip, FOSSiBOT, Fourel, Four Mobile, FOX, Foxconn, FoxxD, FPT, free, Freetel, FreeYond, FRESH, Frunsi, Fuego, FUJICOM, Fujitsu, Funai, Fusion5, Future Mobile Technology, Fxtec, G-Guard, G-PLUS, G-Tab, G-TiDE, G-Touch, G-Vill, Galactic, Galatec, Galaxy Innovations, Gamma, Garmin-Asus, Gateway, Gazal, Gazer, GDL, Geanee, Geant, Gear Mobile, Gemini, General Mobile, Genesis, Genius Devices, GEOFOX, Geo Phone, Geotel, Geotex, GEOZON, Getnord, GFive, Gfone, Ghia, Ghong, Ghost, Gigabyte, Gigaset, Gini, Ginzzu, Gionee, GIRASOLE, GlobalSec, Globex, Globmall, GlocalMe, Glofiish, GLONYX, Glory Star, GLX, GN Electronics, GOCLEVER, Gocomma, GoGEN, GOLDBERG, GoldMaster, GoldStar, Gol Mobile, Goly, Gome, GoMobile, GOODTEL, Google, Goophone, Gooweel, GOtv, Gplus, Gradiente, Graetz, Grape, Great Asia, Gree, Green Lion, Green Orange, Greentel, Gresso, Gretel, GroBerwert, Grundig, Grünberg, Gtel, GTMEDIA, GTX, Guophone, GVC Pro, H96, H133, Hafury, Haier, Haipai, Haixu, Hamlet, Hammer, Handheld, HannSpree, Hanseatic, Hanson, HAOQIN, HAOVM, Hardkernel, Harper, Hartens, Hasee, Hathway, HAVIT, HDC, HeadWolf, HEC, Heimat, Helio, Hemilton, HERO, HexaByte, Hezire, Hi, Hi-Level, Hiberg, HiBy, HIGH1ONE, Highscreen, HiGrace, HiHi, HiKing, HiMax, Hi Nova, HIPER, Hipstreet, Hiremco, Hisense, Hitachi, Hitech, HKC, HKPro, HMD, hoco, HOFER, Hoffmann, HOLLEBERG, Homatics, Hometech, HOMII, Homtom, Honeywell, HongTop, HONKUAHG, Honor, Hoozo, Hopeland, Horion, Horizon, Horizont, Hosin, HOTACK, Hotel TV Company, Hot Pepper, HOTREALS, Hotwav, How, HP, HTC, Huadoo, Huagan, Huavi, Huawei, Hugerock, Humanware, Humax, HUMElab, Hurricane, Huskee, Hyatta, Hykker, Hyrican, Hytera, Hyundai, Hyve, i-Cherry, I-INN, i-Joy, i-mate, i-mobile, I-Plus, iBall, iBerry, ibowin, iBrit, IconBIT, Icone Gold, iData, IDC, iDino, iDroid, iFIT, iGet, iHome Life, iHunt, I KALL, Ikea, IKI Mobile, iKoMo, iKon, iKonia, IKU Mobile, iLA, iLepo, iLife, iMan, Imaq, iMars, iMI, IMO Mobile, Imose, Impression, iMuz, iNavi, INCAR, Inch, Inco, Indurama, iNew, Infiniton, InfinityPro, Infinix, InFocus, InfoKit, Infomir, InFone, Inhon, Inka, Inkti, InnJoo, Inno Hit, Innos, Innostream, Inoi, iNo Mobile, iNOVA, inovo, INQ, Insignia, INSYS, Intek, Intel, Intex, Invens, Inverto, Invin, iOcean, IOTWE, iOutdoor, iPEGTOP, iPro, iQ&T, IQM, IRA, Irbis, iReplace, Iris, iRobot, iRola, iRulu, iSafe Mobile, iStar, iSWAG, IT, iTel, iTruck, IUNI, iVA, iView, iVooMi, ivvi, iWaylink, iXTech, iYou, iZotron, Jambo, JAY-Tech, Jckkcfug, Jeep, Jeka, Jesy, JFone, Jiake, Jiayu, Jide, Jinga, Jin Tu, Jio, Jivi, JKL, Jolla, Joy, JoySurf, JPay, JREN, Jumper, Juniper Systems, Just5, JUSYEA, JVC, JXD, K-Lite, K-Touch, Kaan, Kaiomy, Kalley, Kanji, KAP, Kapsys, Karbonn, Kata, KATV1, Kazam, Kazuna, KDDI, Kempler & Strauss, Kenbo, Kendo, Keneksi, KENSHI, KENWOOD, Kenxinda, KGTEL, Khadas, Kiano, kidiby, Kingbox, Kingelon, Kingstar, Kingsun, KINGZONE, Kinstone, Kiowa, Kivi, Klipad, KMC, KN Mobile, Kocaso, Kodak, Kogan, Komu, Konka, Konrow, Koobee, Koolnee, Kooper, KOPO, Korax, Koridy, Koslam, Kraft, KREZ, KRIP, KRONO, Krüger&Matz, KT-Tech, KTC, KUBO, KuGou, Kuliao, Kult, Kumai, Kurio, KVADRA, Kvant, Kydos, Kyocera, Kyowon, Kzen, KZG, L-Max, LAGENIO, LAIQ, Land Rover, Landvo, Lanin, Lanix, Lark, Laser, Laurus, Lava, LCT, Leader Phone, Leagoo, Leben, LeBest, Lectrus, Ledstar, LeEco, Leelbox, Leff, Legend, Leke, Lemco, LEMFO, Lemhoov, Lenco, Lenovo, Leotec, Le Pan, Lephone, Lesia, Lexand, Lexibook, LG, Liberton, Lifemaxx, Lime, Lingbo, Lingwin, Linnex, Linsar, Linsay, Listo, LNMBBS, Loewe, LOGAN, Logic, Logic Instrument, Logicom, Logik, Logitech, LOKMAT, LongTV, Loview, Lovme, LT Mobile, Lumigon, Lumitel, Lumus, Luna, LUNNEN, LUO, Luxor, Lville, LW, LYF, LYOTECH LABS, M-Horse, M-KOPA, M-Tech, M.T.T., M3 Mobile, M4tel, MAC AUDIO, Macoox, Mafe, MAG, MAGCH, Magenta, Magicsee, Magnus, Majestic, Malata, Mango, Manhattan, Mann, Manta Multimedia, Mantra, Mara, Marshal, Mascom, Massgo, Masstel, Master-G, Mastertech, Matco Tools, Matrix, Maunfeld, Maxcom, Maxfone, Maximus, Maxtron, MAXVI, Maxwell, Maxwest, MAXX, Maze, Maze Speed, MBI, MBK, MBOX, McLaut, MDC Store, meanIT, Mecer, MECHEN, Mecool, Mediacom, Medion, MEEG, Megacable, MegaFon, MEGAMAX, MEGA VISION, Meitu, Meizu, Melrose, MeMobile, Memup, MEO, MESWAO, Meta, Metz, MEU, Microlab, MicroMax, Microsoft, Microtech, Mightier, MIIA, Minix, Mint, Mintt, Mio, Mione, mipo, Miray, Mitchell & Brown, Mito, Mitsubishi, Mitsui, MIVO, MIWANG, MIXC, MiXzo, MLLED, MLS, Mobell, Mobicel, MobiIoT, Mobiistar, Mobile Kingdom, Mobiola, Mobistel, MobiWire, Mobo, Mobvoi, Mode 1, Modecom, Mode Mobile, Mofut, Moondrop, MORTAL, Mosimosi, Motiv, Motorola, Motorola Solutions, Movic, MOVISUN, Movitel, Moxee, mPhone, Mpman, MSI, MStar, MTC, MTN, multibox, Multilaser, MultiPOS, MULTYNET, MwalimuPlus, MYFON, MyGica, MygPad, Mymaga, MyMobile, MyPhone (PH), myPhone (PL), Myria, Myros, Mystery, MyTab, MyWigo, N-one, Nabi, NABO, Nanho, Naomi Phone, NASCO, National, Navcity, Navitech, Navitel, Navon, NavRoad, NEC, Necnot, Nedaphone, Neffos, NEKO, Neo, neoCore, Neolix, Neomi, Neon IQ, Neoregent, Nesons, NetBox, Netgear, Netmak, NETWIT, NeuImage, NeuTab, NEVIR, Newal, New Balance, New Bridge, Newgen, Newland, Newman, Newsday, NewsMy, Nexa, Nexar, NEXBOX, Nexian, NEXON, NEXT, Next & NextStar, Nextbit, NextBook, NextTab, NGM, NG Optics, NGpon, Nikon, NILAIT, NINETEC, NINETOLOGY, Nintendo, nJoy, NOA, Noain, Nobby, Noblex, NOBUX, noDROPOUT, NOGA, Nokia, Nomi, Nomu, Noontec, Nordfrost, Nordmende, NORMANDE, NorthTech, Nos, Nothing, Nous, Novacom, Novex, Novey, NOVIS, NoviSea, NOVO, NTT West, NuAns, Nubia, NUU Mobile, NuVision, Nuvo, Nvidia, NYX Mobile, O+, O2, Oale, Oangcc, OASYS, Obabox, Ober, Obi, OCEANIC, Odotpad, Odys, Oilsky, OINOM, ok., Okapi, Okapia, Oking, OKSI, OKWU, Olax, Olkya, Ollee, OLTO, Olympia, OMIX, Onda, OneClick, OneLern, OnePlus, Onida, Onix, Onkyo, ONN, ONVO, ONYX BOOX, Ookee, Ooredoo, OpelMobile, Openbox, Ophone, OPPO, Opsson, Optoma, Orange, Orange Pi, Orava, Orbic, Orbita, Orbsmart, Ordissimo, Orion, OSCAL, OTT, OTTO, OUJIA, Ouki, Oukitel, OUYA, Overmax, Ovvi, Owwo, OX TAB, OYSIN, Oysters, Oyyu, OzoneHD, Pacific Research Alliance, Packard Bell, PAGRAER, Paladin, Palm, Panacom, Panasonic, Panavox, Pano, Panodic, Panoramic, Pantech, PAPYRE, Parrot Mobile, Partner Mobile, PCBOX, PCD, PCD Argentina, PC Smart, PEAQ, Pelitt, Pendoo, Penta, Pentagram, Perfeo, Phicomm, Philco, Philips, Phonemax, phoneOne, Pico, PINE64, Pioneer, Pioneer Computers, PiPO, PIRANHA, Pixela, Pixelphone, PIXPRO, Pixus, Planet Computers, Platoon, Play Now, PLDT, Ployer, Plum, PlusStyle, Pluzz, PocketBook, POCO, Point Mobile, Point of View, Polar, PolarLine, Polaroid, Polestar, PolyPad, Polytron, Pomp, Poppox, POPTEL, Porsche, Portfolio, Positivo, Positivo BGH, Powerway, PPDS, PPTV, PREMIER, Premier Star, Premio, Prestigio, PRIME, Primepad, Primux, PRISM+, Pritom, Prixton, PROFiLO, Proline, Prology, ProScan, PROSONIC, Protruly, ProVision, PULID, Punos, Purism, PVBox, Q-Box, Q-Touch, Q.Bell, QFX, Qilive, QIN, Qiuwoky, QLink, QMobile, Qnet Mobile, QTECH, Qtek, Quanta Computer, Quantum, Quatro, Qubo, Quechua, Quest, Quipus, Qumo, Qupi, Qware, QWATT, R-TV, R3Di, Rakuten, Ramos, Raspberry, Ravoz, Raylandz, Razer, RAZZ, RCA Tablets, RCT, Reach, Readboy, Realix, Realme, RED, RED-X, Redbean, Redfox, RedLine, Redway, Reeder, REGAL, RelNAT, Relndoo, Remdun, Renova, RENSO, rephone, Retroid Pocket, Revo, Revomovil, Rhino, Ricoh, Rikomagic, RIM, Ringing Bells, Rinno, Ritmix, Ritzviva, Riviera, Rivo, Rizzen, ROADMAX, Roadrover, Roam Cat, ROCH, Rocket, Rokit, Roku, Rombica, Romsat, Ross&Moor, Rover, Rover Computers, Royole, RoyQueen, RTK, RT Project, RugGear, RuggeTech, Ruggex, Ruio, Runbo, RunGee, Rupa, Ryte, S-Color, S-TELL, S2Tel, Saba, Safaricom, Sagem, Sagemcom, Saiet, SAILF, Salora, Sambox, Samsung, Samtech, Samtron, Sanei, Sankey, Sansui, Santin, SANY, Sanyo, Savio, Sber, SCHAUB LORENZ, Schneider, Schok, SCHONTECH, Scoole, Scosmos, Seatel, SEBBE, Seeken, SEEWO, SEG, Sega, SEHMAX, Selecline, Selenga, Selevision, Selfix, SEMP TCL, Sencor, Sencrom, Sendo, Senkatel, SENNA, Senseit, Senwa, SERVO, Seuic, Sewoo, SFR, SGIN, Shanling, Sharp, Shift Phones, Shivaki, Shtrikh-M, Shuttle, Sico, Siemens, Sigma, Silelis, Silent Circle, Silva Schneider, Simbans, simfer, Simply, SINGER, Singtech, Siragon, Sirin Labs, Siswoo, SK Broadband, SKG, SKK Mobile, Sky, Skyline, SkyStream, Skytech, Skyworth, Smadl, Smailo, Smart, Smartab, SmartBook, SMARTEC, Smart Electronic, Smartex, Smartfren, Smartisan, Smart Kassel, Smart Tech, Smarty, Smooth Mobile, Smotreshka, SMT Telecom, SMUX, SNAMI, SobieTech, Soda, Softbank, Soho Style, Solas, SOLE, SOLO, Solone, Sonim, SONOS, Sony, Sony Ericsson, SOSH, SoulLink, Soundmax, SOWLY, Soyes, Spark NZ, Sparx, SPC, Spectralink, Spectrum, Spice, Spider, SPURT, SQOOL, SSKY, Ssmart, Star-Light, Starlight, Starmobile, Starway, Starwind, STF Mobile, STG Telecom, Stilevs, STK, Stonex, Storex, StrawBerry, StreamSystem, STRONG, Stylo, SUAAT, Subor, Sugar, SULPICE TV, Sumvision, SUNGATE, Sunmax, Sunmi, Sunny, Sunstech, SunVan, Sunvell, SUNWIND, SuperBOX, Super General, Supermax, SuperSonic, SuperTab, SuperTV, Supra, Supraim, Surfans, Surge, Suzuki, Sveon, Swipe, SWISSMOBILITY, Swisstone, Switel, SWOFY, Syco, SYH, Sylvania, Symphony, Syrox, System76, SZ TPS, T-Mobile, T96, TADAAM, TAG Tech, Taiga System, Takara, TALBERG, Talius, Tambo, Tanix, TAUBE, TB Touch, TCL, TCL SCBC, TD Systems, TD Tech, TeachTouch, Techmade, Technicolor, Technika, TechniSat, Technopc, TECHNOSAT, TechnoTrend, TechPad, Techstorm, Techwood, Teclast, Tecno Mobile, TecToy, TEENO, Teknosa, Tele2, Telefunken, Telego, Telenor, Telia, Telit, Telkom, Telly, Telma, TeloSystems, Telpo, Temigereev, TENPLUS, Teracube, Terra, Tesco, Tesla, TETC, Tetratab, teXet, ThL, Thomson, Thuraya, TIANYU, Tibuta, Tigers, Time2, Timovi, TIMvision, Tinai, Tinmo, TiPhone, Tivax, TiVo, TJC, TJD, TOKYO, Tolino, Tone, TOOGO, Tooky, Top-Tech, TopDevice, TOPDON, Topelotek, Top House, Toplux, TOPSHOWS, Topsion, Topway, Torex, TORNADO, Torque, TOSCIDO, Toshiba, Touchmate, Touch Plus, TOX, Transpeed, Trecfone, TrekStor, Trevi, TriaPlay, Tricolor, Trident, Trifone, Trimble, Trio, Tronsmart, True, True Slim, Tsinghua Tongfang, TTEC, TTfone, TTK-TV, TuCEL, TUCSON, Tunisie Telecom, Turbo, Turbo-X, TurboKids, TurboPad, Turkcell, Tuvio, TV+, TVC, TwinMOS, TWM, TWZ Corporation, TYD, Tymes, Türksat, Türk Telekom, U-Magic, U.S. Cellular, UD, UGINE, Ugoos, Uhans, Uhappy, Ulefone, Umax, UMIDIGI, Umiio, Unblock Tech, Uniden, Unihertz, Unikalne Smartphones, Unimax, Uniqcell, Uniscope, Unistrong, Unitech, UNITED, United Group, UNIWA, Unknown, Unnecto, Unnion Technologies, UNNO, Unonu, UnoPhone, Unowhy, UOOGOU, Urovo, UTime, UTOK, UTStarcom, UZ Mobile, V-Gen, V-HOME, V-HOPE, v-mobile, V7, VAIO, VALE, VALEM, VALTECH, VANGUARD, Vankyo, VANWIN, Vargo, VASOUN, Vastking, VAVA, VC, VDVD, Vega, Veidoo, Vekta, Venso, Venstar, Venturer, VEON, Verico, Verizon, Vernee, Verssed, Versus, Vertex, Vertu, Verykool, Vesta, Vestel, VETAS, Vexia, VGO TEL, ViBox, Victurio, VIDA, Videocon, Videoweb, Viendo, ViewSonic, VIIPOO, VIKUSHA, VILLAON, VIMOQ, Vinabox, Vinga, Vinsoc, Vios, Viper, Vipro, Virzo, Vision Technology, Vision Touch, Visitech, Visual Land, Vitelcom, Vitumi, Vityaz, Viumee, Vivax, VIVIBright, VIVIMAGE, Vivo, VIWA, Vizio, Vizmo, VK Mobile, VKworld, VNPT Technology, VOCAL, Vodacom, Vodafone, VOGA, VOIX, VOLIA, VOLKANO, Volla, Volt, Vonino, Vontar, Vorago, Vorcom, Vorke, Vormor, Vortex, VORTEX (RO), Voto, VOX Electronics, Voxtel, Voyo, Vsmart, Vsun, VUCATIMES, Vue Micro, Vulcan, VVETIME, Völfen, W&O, WAF, Wainyok, waipu.tv, Walker, Waltham, Walton, Waltter, WANSA, WE, We. by Loewe., Webfleet, Web TV, WeChip, Wecool, Weelikeit, Weiimi, Weimei, WellcoM, WELLINGTON, Western Digital, Weston, Westpoint, Wexler, Whoop, Wieppo, Wigor, Wiko, WildRed, Wileyfox, Winds, Wink, Winmax, Winnovo, Winstar, Wintouch, Wiseasy, WIWA, WizarPos, Wizz, Wolder, Wolfgang, Wolki, WONDER, Wonu, Woo, Woxter, WOZIFAN, WS, X-AGE, X-BO, X-Mobile, X-TIGI, X-View, X.Vision, X88, X96, X96Q, XB, Xcell, XCOM, Xcruiser, XElectron, XGEM, XGIMI, Xgody, Xiaodu, Xiaolajiao, Xiaomi, Xion, Xolo, Xoro, XPPen, XREAL, Xshitou, Xsmart, Xtouch, Xtratech, Xwave, XY Auto, Yandex, Yarvik, YASIN, YELLYOUTH, YEPEN, Yes, Yestel, Yezz, YIKEMI, Yoka TV, Yooz, Yota, YOTOPT, Youin, Youwei, Ytone, Yu, Yuandao, YU Fly, YUHO, YUMKEM, YUNDOO, Yuno, YunSong, Yusun, Yxtel, Z-Kai, Zaith, ZALA, Zamolxe, Zatec, Zealot, Zeblaze, Zebra, Zeeker, Zeemi, Zen, Zenek, Zentality, Zfiner, ZH&K, Zhongyu Display, Zidoo, ZIFFLER, ZIFRO, Zigo, ZIK, Zimmer, Zinox, ZIOVO, Ziox, Zonda, Zonko, Zoom, ZoomSmart, Zopo, ZTE, Zuum, Zync, ZYQ, Zyrex, ZZB, öwn',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_DeviceBrand',
    ],
    20 => [
        'type' => 'dimension',
        'segment' => 'deviceModel',
        'acceptedValues' => 'iPad, Nexus 5, Galaxy S5, Fire TV, etc.',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_DeviceModel',
    ],
    21 => [
        'type' => 'dimension',
        'segment' => 'deviceType',
        'acceptedValues' => 'desktop, smartphone, tablet, feature phone, console, tv, car browser, smart display, camera, portable media player, phablet, smart speaker, wearable, peripheral',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_DeviceType',
    ],
    22 => [
        'type' => 'dimension',
        'segment' => 'fingerprint',
        'acceptedValues' => '1eceaa833348b187 - any 16 Hexadecimal chars ID, which can be fetched from API.getLastVisitsDetails',
        'permission' => '1',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_VisitorFingerprint',
    ],
    23 => [
        'type' => 'dimension',
        'segment' => 'visitLocalHour',
        'acceptedValues' => '0, 1, 2, 3, ..., 20, 21, 22, 23',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnLocalHour',
    ],
    24 => [
        'type' => 'dimension',
        'segment' => 'operatingSystemName',
        'acceptedValues' => 'Windows, Linux, Mac, Android, iOS etc.',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_ColumnOperatingSystem',
    ],
    25 => [
        'type' => 'dimension',
        'segment' => 'operatingSystemCode',
        'acceptedValues' => 'WIN, LIN, MAX, AND, IOS etc.',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_OperatingSystemCode',
    ],
    26 => [
        'type' => 'dimension',
        'segment' => 'operatingSystemVersion',
        'acceptedValues' => 'XP, 7, 2.3, 5.1, ...',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'DevicesDetection_ColumnOperatingSystemVersion',
    ],
    27 => [
        'type' => 'dimension',
        'segment' => 'profilable',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'CoreHome_Profilable',
        'acceptedValuesKey' => 'CoreHome_ProfilableSegmentHelp',
    ],
    28 => [
        'type' => 'dimension',
        'segment' => 'resolution',
        'acceptedValues' => '1280x1024, 800x600, etc.',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'Resolution_ColumnResolution',
    ],
    29 => [
        'type' => 'dimension',
        'segment' => 'visitStartServerHour',
        'acceptedValues' => '0, 1, 2, 3, ..., 20, 21, 22, 23',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitStartSiteHour',
    ],
    30 => [
        'type' => 'dimension',
        'segment' => 'visitServerHour',
        'acceptedValues' => '0, 1, 2, 3, ..., 20, 21, 22, 23',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndSiteHour',
    ],
    31 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerDate',
        'acceptedValues' => '2018-12-31, 2018-03-20, ...',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCDate',
    ],
    32 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerDayOfMonth',
        'acceptedValues' => '0, 1, 2, 3, ..., 29, 30, 31',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCDayOfMonth',
    ],
    33 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerDayOfWeek',
        'acceptedValues' => '1, 2, 3, 4, 5, 6, 7',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCDayOfWeek',
    ],
    34 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerDayOfYear',
        'acceptedValues' => '1, 2, 3, 4, ..., 365, 366',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCDayOfYear',
    ],
    35 => [
        'type' => 'dimension',
        'segment' => 'visitStartServerMinute',
        'acceptedValues' => '0, 1, 2, 3, ..., 56, 57, 58, 59',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitStartUTCMinute',
    ],
    36 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerMinute',
        'acceptedValues' => '0, 1, 2, 3, ..., 56, 57, 58, 59',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCMinute',
    ],
    37 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerMonth',
        'acceptedValues' => '1, 2, 3, ..., 11, 12',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCMonth',
    ],
    38 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerQuarter',
        'acceptedValues' => '1, 2, 3, 4',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCQuarter',
    ],
    39 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerSecond',
        'acceptedValues' => '0, 1, 2, 3, ..., 58, 59',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCSecond',
    ],
    40 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerWeekOfYear',
        'acceptedValues' => '1, 2, 3, 4, ..., 51, 52, 53',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCWeekOfYear',
    ],
    41 => [
        'type' => 'dimension',
        'segment' => 'visitEndServerYear',
        'acceptedValues' => '2016, 2017, 2018, ..., 9998, 9999',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'VisitTime_ColumnVisitEndUTCYear',
    ],
    42 => [
        'type' => 'dimension',
        'segment' => 'userId',
        'permission' => '1',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_UserId',
        'acceptedValuesKey' => 'UserId_UserIdSegmentHelp',
    ],
    43 => [
        'type' => 'dimension',
        'segment' => 'visitEcommerceStatus',
        'acceptedValues' => 'none, ordered, abandonedCart, orderedThenAbandonedCart. For example, to select all visits that have made an Ecommerce order, the API request would contain "&segment=visitEcommerceStatus==ordered,visitEcommerceStatus==orderedThenAbandonedCart"',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_EcommerceVisitStatusDesc',
    ],
    44 => [
        'type' => 'dimension',
        'segment' => 'visitId',
        'permission' => '1',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_VisitId',
        'acceptedValuesKey' => 'General_AnyPositiveInteger',
    ],
    45 => [
        'type' => 'dimension',
        'segment' => 'visitConvertedGoalId',
        'acceptedValues' => '1, 2, 3, etc.',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_VisitConvertedGoalId',
    ],
    46 => [
        'type' => 'dimension',
        'segment' => 'visitConvertedGoalName',
        'acceptedValues' => 'myGoal, myOtherGoal, etc.',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_VisitConvertedGoalName',
    ],
    47 => [
        'type' => 'dimension',
        'segment' => 'visitConverted',
        'acceptedValues' => '0, 1',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_VisitConvertedGoal',
    ],
    48 => [
        'type' => 'dimension',
        'segment' => 'visitorType',
        'acceptedValues' => 'new, returning, returningCustomer. For example, to select all visitors who have returned to the website, including those who have bought something in their previous visits, the API request would contain "&segment=visitorType==returning,visitorType==returningCustomer"',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_VisitType',
    ],
    49 => [
        'type' => 'dimension',
        'segment' => 'visitorId',
        'acceptedValues' => '34c31e04394bdc63 - any 16 Hexadecimal chars ID, which can be fetched using the Tracking API function getVisitorId()',
        'permission' => '1',
        'categoryKey' => 'General_Visitors',
        'nameKey' => 'General_VisitorID',
    ],
    50 => [
        'type' => 'dimension',
        'segment' => 'city',
        'acceptedValues' => 'Sydney, Sao Paolo, Rome, etc.',
        'categoryKey' => 'UserCountry_VisitLocation',
        'nameKey' => 'UserCountry_City',
    ],
    51 => [
        'type' => 'dimension',
        'segment' => 'continentCode',
        'acceptedValues' => 'eur, asi, amc, amn, ams, afr, ant, oce',
        'categoryKey' => 'UserCountry_VisitLocation',
        'nameKey' => 'UserCountry_Continent',
    ],
    52 => [
        'type' => 'dimension',
        'segment' => 'countryName',
        'acceptedValues' => 'Germany, France, Spain, ...',
        'categoryKey' => 'UserCountry_VisitLocation',
        'nameKey' => 'UserCountry_Country',
    ],
    53 => [
        'type' => 'dimension',
        'segment' => 'countryCode',
        'categoryKey' => 'UserCountry_VisitLocation',
        'nameKey' => 'UserCountry_CountryCode',
        'acceptedValuesKey' => 'UserCountry_CountrySegmentHelp',
    ],
    54 => [
        'type' => 'dimension',
        'segment' => 'languageCode',
        'acceptedValues' => 'de, fr, en-gb, zh-cn, etc.',
        'categoryKey' => 'UserCountry_VisitLocation',
        'nameKey' => 'General_Language',
    ],
    55 => [
        'type' => 'dimension',
        'segment' => 'latitude',
        'acceptedValues' => '-33.578, 40.830, etc.<br/>You can select visitors within a lat/long range using &segment=lat>X;lat<Y;long>M;long<N.',
        'categoryKey' => 'UserCountry_VisitLocation',
        'nameKey' => 'UserCountry_Latitude',
    ],
    56 => [
        'type' => 'dimension',
        'segment' => 'longitude',
        'acceptedValues' => '-70.664, 14.326, etc.',
        'categoryKey' => 'UserCountry_VisitLocation',
        'nameKey' => 'UserCountry_Longitude',
    ],
    57 => [
        'type' => 'dimension',
        'segment' => 'regionCode',
        'acceptedValues' => '01, 02, OR, P8,…<br/>eg. region=BFC;country=fr',
        'categoryKey' => 'UserCountry_VisitLocation',
        'nameKey' => 'UserCountry_Region',
    ],
    58 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name (scope visit)',
        'segment' => 'customVariableName',
        'unionOfSegments' => [
            0 => 'customVariableName1',
            1 => 'customVariableName2',
            2 => 'customVariableName3',
            3 => 'customVariableName4',
            4 => 'customVariableName5',
        ],
    ],
    59 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 1 (scope visit)',
        'segment' => 'customVariableName1',
    ],
    60 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 2 (scope visit)',
        'segment' => 'customVariableName2',
    ],
    61 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 3 (scope visit)',
        'segment' => 'customVariableName3',
    ],
    62 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 4 (scope visit)',
        'segment' => 'customVariableName4',
    ],
    63 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 5 (scope visit)',
        'segment' => 'customVariableName5',
    ],
    64 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name (scope page)',
        'segment' => 'customVariablePageName',
        'unionOfSegments' => [
            0 => 'customVariablePageName1',
            1 => 'customVariablePageName2',
            2 => 'customVariablePageName3',
            3 => 'customVariablePageName4',
            4 => 'customVariablePageName5',
        ],
    ],
    65 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 1 (scope page)',
        'segment' => 'customVariablePageName1',
    ],
    66 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 2 (scope page)',
        'segment' => 'customVariablePageName2',
    ],
    67 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 3 (scope page)',
        'segment' => 'customVariablePageName3',
    ],
    68 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 4 (scope page)',
        'segment' => 'customVariablePageName4',
    ],
    69 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable name 5 (scope page)',
        'segment' => 'customVariablePageName5',
    ],
    70 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value (scope page)',
        'segment' => 'customVariablePageValue',
        'unionOfSegments' => [
            0 => 'customVariablePageValue1',
            1 => 'customVariablePageValue2',
            2 => 'customVariablePageValue3',
            3 => 'customVariablePageValue4',
            4 => 'customVariablePageValue5',
        ],
    ],
    71 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 1 (scope page)',
        'segment' => 'customVariablePageValue1',
    ],
    72 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 2 (scope page)',
        'segment' => 'customVariablePageValue2',
    ],
    73 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 3 (scope page)',
        'segment' => 'customVariablePageValue3',
    ],
    74 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 4 (scope page)',
        'segment' => 'customVariablePageValue4',
    ],
    75 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 5 (scope page)',
        'segment' => 'customVariablePageValue5',
    ],
    76 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value (scope visit)',
        'segment' => 'customVariableValue',
        'unionOfSegments' => [
            0 => 'customVariableValue1',
            1 => 'customVariableValue2',
            2 => 'customVariableValue3',
            3 => 'customVariableValue4',
            4 => 'customVariableValue5',
        ],
    ],
    77 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 1 (scope visit)',
        'segment' => 'customVariableValue1',
    ],
    78 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 2 (scope visit)',
        'segment' => 'customVariableValue2',
    ],
    79 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 3 (scope visit)',
        'segment' => 'customVariableValue3',
    ],
    80 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 4 (scope visit)',
        'segment' => 'customVariableValue4',
    ],
    81 => [
        'type' => 'dimension',
        'category' => 'Custom Variables',
        'name' => 'Custom Variable value 5 (scope visit)',
        'segment' => 'customVariableValue5',
    ],
    82 => [
        'type' => 'metric',
        'name' => 'Bandwidth',
        'segment' => 'bandwidth',
        'acceptedValues' => 'Any number in bytes, eg. 1000',
        'categoryKey' => 'Actions_Behaviour',
    ],
    83 => [
        'type' => 'dimension',
        'segment' => 'actionType',
        'acceptedValues' => 'A type of action, such as: pageviews, contents, sitesearches, events, outlinks, downloads',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_ActionType',
    ],
    84 => [
        'type' => 'dimension',
        'segment' => 'actionUrl',
        'unionOfSegments' => [
            0 => 'pageUrl',
            1 => 'downloadUrl',
            2 => 'outlinkUrl',
            3 => 'eventUrl',
        ],
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_ColumnActionURL',
    ],
    85 => [
        'type' => 'dimension',
        'segment' => 'siteSearchCategory',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_SiteSearchCategory',
    ],
    86 => [
        'type' => 'dimension',
        'segment' => 'outlinkUrl',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_ColumnClickedURL',
    ],
    87 => [
        'type' => 'dimension',
        'segment' => 'contentInteraction',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Contents_ContentInteraction',
        'acceptedValuesKey' => 'Contents_ContentInteractionSegmentHelp',
    ],
    88 => [
        'type' => 'dimension',
        'segment' => 'contentName',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Contents_ContentName',
        'acceptedValuesKey' => 'Contents_ContentNameSegmentHelp',
    ],
    89 => [
        'type' => 'dimension',
        'segment' => 'contentPiece',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Contents_ContentPiece',
        'acceptedValuesKey' => 'Contents_ContentPieceSegmentHelp',
    ],
    90 => [
        'type' => 'dimension',
        'segment' => 'contentTarget',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Contents_ContentTarget',
        'acceptedValuesKey' => 'Contents_ContentTargetSegmentHelp',
    ],
    91 => [
        'type' => 'dimension',
        'segment' => 'downloadUrl',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_ColumnDownloadURL',
    ],
    92 => [
        'type' => 'dimension',
        'segment' => 'entryPageUrl',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_ColumnEntryPageURL',
    ],
    93 => [
        'type' => 'dimension',
        'segment' => 'entryPageTitle',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_ColumnEntryPageTitle',
    ],
    94 => [
        'type' => 'dimension',
        'segment' => 'exitPageTitle',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_ColumnExitPageTitle',
    ],
    95 => [
        'type' => 'dimension',
        'segment' => 'exitPageUrl',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_ColumnExitPageURL',
    ],
    96 => [
        'type' => 'dimension',
        'segment' => 'siteSearchKeyword',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_SiteSearchKeyword',
    ],
    97 => [
        'type' => 'dimension',
        'segment' => 'siteSearchCount',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_SiteSearchKeywordCount',
    ],
    98 => [
        'type' => 'dimension',
        'segment' => 'pageTitle',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Goals_PageTitle',
    ],
    99 => [
        'type' => 'dimension',
        'segment' => 'pageUrl',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'Actions_ColumnPageURL',
    ],
    100 => [
        'type' => 'dimension',
        'segment' => 'actionServerHour',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'VisitTime_ColumnSiteHour',
    ],
    101 => [
        'type' => 'dimension',
        'segment' => 'actionServerMinute',
        'acceptedValues' => '0, 1, 2, 3, ..., 56, 57, 58, 59',
        'categoryKey' => 'Actions_Behaviour',
        'nameKey' => 'VisitTime_ColumnUTCMinute',
    ],
    102 => [
        'type' => 'metric',
        'segment' => 'eventValue',
        'categoryKey' => 'Events_Events',
        'nameKey' => 'Events_EventValue',
    ],
    103 => [
        'type' => 'dimension',
        'segment' => 'eventAction',
        'categoryKey' => 'Events_Events',
        'nameKey' => 'Events_EventAction',
    ],
    104 => [
        'type' => 'dimension',
        'segment' => 'eventCategory',
        'categoryKey' => 'Events_Events',
        'nameKey' => 'Events_EventCategory',
    ],
    105 => [
        'type' => 'dimension',
        'segment' => 'eventName',
        'categoryKey' => 'Events_Events',
        'nameKey' => 'Events_EventName',
    ],
    106 => [
        'type' => 'dimension',
        'segment' => 'eventUrl',
        'acceptedValues' => 'The URL must be URL encoded, for example: http%3A%2F%2Fexample.com%2Fpath%2Fpage%3Fquery',
        'categoryKey' => 'Events_Events',
        'nameKey' => 'Events_EventUrl',
    ],
    107 => [
        'type' => 'dimension',
        'segment' => 'referrerType',
        'acceptedValues' => 'direct, search, website, campaign, ai',
        'categoryKey' => 'Referrers_Acquisition',
        'nameKey' => 'Referrers_Type',
    ],
    108 => [
        'type' => 'dimension',
        'segment' => 'referrerKeyword',
        'acceptedValues' => 'Encoded%20Keyword, keyword',
        'categoryKey' => 'Referrers_Acquisition',
        'nameKey' => 'General_ColumnKeyword',
    ],
    109 => [
        'type' => 'dimension',
        'segment' => 'referrerName',
        'acceptedValues' => 'twitter.com, www.facebook.com, Bing, Google, Yahoo, CampaignName',
        'categoryKey' => 'Referrers_Acquisition',
        'nameKey' => 'Referrers_ReferrerName',
    ],
    110 => [
        'type' => 'dimension',
        'segment' => 'referrerUrl',
        'acceptedValues' => 'http%3A%2F%2Fwww.example.org%2Freferer-page.htm',
        'categoryKey' => 'Referrers_Acquisition',
        'nameKey' => 'Live_Referrer_URL',
    ],
    111 => [
        'type' => 'metric',
        'segment' => 'orderId',
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Ecommerce_OrderId',
    ],
    112 => [
        'type' => 'metric',
        'segment' => 'revenueOrder',
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Ecommerce_OrderRevenue',
    ],
    113 => [
        'type' => 'metric',
        'segment' => 'productPrice',
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Goals_ProductPrice',
    ],
    114 => [
        'type' => 'metric',
        'segment' => 'revenueAbandonedCart',
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Ecommerce_RevenueLeftInCart',
    ],
    115 => [
        'type' => 'metric',
        'segment' => 'productViewPrice',
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Ecommerce_ViewedProductPrice',
    ],
    116 => [
        'type' => 'dimension',
        'segment' => 'productCategory',
        'unionOfSegments' => [
            0 => 'productCategory1',
            1 => 'productCategory2',
            2 => 'productCategory3',
            3 => 'productCategory4',
            4 => 'productCategory5',
        ],
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Goals_ProductCategory',
    ],
    117 => [
        'type' => 'dimension',
        'segment' => 'productName',
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Goals_ProductName',
    ],
    118 => [
        'type' => 'dimension',
        'segment' => 'productSku',
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Goals_ProductSKU',
    ],
    119 => [
        'type' => 'dimension',
        'segment' => 'productViewCategory',
        'unionOfSegments' => [
            0 => 'productViewCategory1',
            1 => 'productViewCategory2',
            2 => 'productViewCategory3',
            3 => 'productViewCategory4',
            4 => 'productViewCategory5',
        ],
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Ecommerce_ViewedProductCategory',
    ],
    120 => [
        'type' => 'dimension',
        'segment' => 'productViewName',
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Ecommerce_ViewedProductName',
    ],
    121 => [
        'type' => 'dimension',
        'segment' => 'productViewSku',
        'categoryKey' => 'Goals_Ecommerce',
        'nameKey' => 'Ecommerce_ViewedProductSKU',
    ],
];
